version : 3

tasks:
  build:
    cmds:
      - go build -o bin/adori cmd/main.go
  run:
    cmds:
      - task build
      - ./bin/adori --config example_config.yaml
  install:
    cmds:
      - task build
      - mv bin/adori ~/go/bin